# Generated by Django 4.2.3 on 2023-08-11 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('idx', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=50)),
                ('opendate', models.CharField(max_length=500)),
                ('people', models.CharField(max_length=500)),
                ('grade', models.CharField(max_length=20, null=True)),
                ('genre', models.CharField(max_length=20)),
                ('repnation', models.CharField(max_length=20, null=True)),
                ('nations', models.CharField(max_length=20, null=True)),
                ('Production', models.CharField(max_length=20, null=True)),
                ('distributor', models.CharField(max_length=20, null=True)),
                ('director', models.CharField(max_length=20, null=True)),
                ('actors', models.CharField(max_length=20, null=True)),
                ('story', models.CharField(max_length=20, null=True)),
                ('keyword', models.CharField(max_length=20, null=True)),
            ],
        ),
    ]
