# Generated by Django 4.2.3 on 2023-08-17 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_alter_movie_actors_alter_movie_director_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('userid', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('passwd', models.CharField(max_length=500)),
                ('name', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=20)),
                ('tel', models.CharField(max_length=20, null=True)),
            ],
        ),
    ]
