# Generated by Django 4.2.3 on 2023-08-17 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_member'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('idx', models.AutoField(primary_key=True, serialize=False)),
                ('userid', models.CharField(max_length=50)),
                ('query', models.CharField(max_length=500)),
                ('answer', models.CharField(max_length=1000)),
                ('intent', models.CharField(max_length=50)),
            ],
        ),
    ]
