# Generated by Django 4.2.3 on 2023-08-25 07:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0007_movie_review_movie_revscore_movie_totscore'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='review',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='revscore',
        ),
    ]
