# Generated by Django 4.2.3 on 2023-08-25 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0008_remove_movie_review_remove_movie_revscore'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='revscore',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
