# Generated by Django 4.2.3 on 2023-08-25 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0009_movie_revscore'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='review',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
