# Generated by Django 4.2.3 on 2023-08-25 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0010_movie_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='review',
            field=models.CharField(max_length=2000, null=True),
        ),
    ]
